### ISSUE TITLE
less changes not working

### ISSUE THREAD

**Issue by menkaff** [krisawzm/blank-bootstrap-theme#1]
i change @brand-primary: #000; like this but it's not working and still the orange color shows , i'm new in less and maybe this question is  have a simple answer. thanks

**Comment by menkaff** [comment]
well actually it's works when i exclude the less folder and again include it :)

**Comment by menkaff** [comment]
of course this is not a solution would you plz guide me? thanks

**Comment by kalfheim** [comment]
Not a "problem" with Less, but rather with OctoberCMS. Have you tried to empty the cache?

Try running

```
php artisan cache:clear
```

after making changes to the Less files.
